export const NAV_ITEMS = [
  { href: "/", label: "Dashboard" },
  { href: "/search", label: "Search" },
  // { href: '/watchlist', label: 'Watchlist' },
];

// Sign-up form select options
export const INVESTMENT_GOALS = [
  { value: "Growth", label: "追求增长" },
  { value: "Income", label: "稳定收益" },
  { value: "Balanced", label: "均衡配置" },
  { value: "Conservative", label: "保值稳健" },
];

export const RISK_TOLERANCE_OPTIONS = [
  { value: "Low", label: "低" },
  { value: "Medium", label: "中" },
  { value: "High", label: "高" },
];

export const PREFERRED_INDUSTRIES = [
  { value: "Technology", label: "科技" },
  { value: "Healthcare", label: "医疗" },
  { value: "Finance", label: "基金" },
  { value: "Energy", label: "能源" },
  { value: "Consumer Goods", label: "大消费" },
];

export const COUNTRIES = [
  "阿富汗",
  "阿尔巴尼亚",
  "阿尔及利亚",
  "安道尔",
  "安哥拉",
  "安提瓜和巴布达",
  "阿根廷",
  "亚美尼亚",
  "澳大利亚",
  "奥地利",
  "阿塞拜疆",
  "巴哈马",
  "巴林",
  "孟加拉国",
  "巴巴多斯",
  "白俄罗斯",
  "比利时",
  "伯利兹",
  "贝宁",
  "不丹",
  "玻利维亚",
  "波黑",
  "博茨瓦纳",
  "巴西",
  "文莱",
  "保加利亚",
  "布基纳法索",
  "布隆迪",
  "佛得角",
  "柬埔寨",
  "喀麦隆",
  "加拿大",
  "中非",
  "乍得",
  "智利",
  "中国",
  "哥伦比亚",
  "科摩罗",
  "刚果（布）",
  "刚果（金）",
  "哥斯达黎加",
  "科特迪瓦",
  "克罗地亚",
  "古巴",
  "塞浦路斯",
  "捷克",
  "丹麦",
  "吉布提",
  "多米尼克",
  "多米尼加",
  "厄瓜多尔",
  "埃及",
  "萨尔瓦多",
  "赤道几内亚",
  "厄立特里亚",
  "爱沙尼亚",
  "斯威士兰",
  "埃塞俄比亚",
  "斐济",
  "芬兰",
  "法国",
  "加蓬",
  "冈比亚",
  "格鲁吉亚",
  "德国",
  "加纳",
  "希腊",
  "格林纳达",
  "危地马拉",
  "几内亚",
  "几内亚比绍",
  "圭亚那",
  "海地",
  "洪都拉斯",
  "匈牙利",
  "冰岛",
  "印度",
  "印度尼西亚",
  "伊朗",
  "伊拉克",
  "爱尔兰",
  "以色列",
  "意大利",
  "牙买加",
  "日本",
  "约旦",
  "哈萨克斯坦",
  "肯尼亚",
  "基里巴斯",
  "科威特",
  "吉尔吉斯斯坦",
  "老挝",
  "拉脱维亚",
  "黎巴嫩",
  "莱索托",
  "利比里亚",
  "利比亚",
  "列支敦士登",
  "立陶宛",
  "卢森堡",
  "马达加斯加",
  "马拉维",
  "马来西亚",
  "马尔代夫",
  "马里",
  "马耳他",
  "马绍尔群岛",
  "毛里塔尼亚",
  "毛里求斯",
  "墨西哥",
  "密克罗尼西亚",
  "摩尔多瓦",
  "摩纳哥",
  "蒙古",
  "黑山",
  "摩洛哥",
  "莫桑比克",
  "缅甸",
  "纳米比亚",
  "瑙鲁",
  "尼泊尔",
  "荷兰",
  "新西兰",
  "尼加拉瓜",
  "尼日尔",
  "尼日利亚",
  "朝鲜",
  "北马其顿",
  "挪威",
  "阿曼",
  "巴基斯坦",
  "帕劳",
  "巴勒斯坦",
  "巴拿马",
  "巴布亚新几内亚",
  "巴拉圭",
  "秘鲁",
  "菲律宾",
  "波兰",
  "葡萄牙",
  "卡塔尔",
  "罗马尼亚",
  "俄罗斯",
  "卢旺达",
  "圣基茨和尼维斯",
  "圣卢西亚",
  "圣文森特和格林纳丁斯",
  "萨摩亚",
  "圣马力诺",
  "圣多美和普林西比",
  "沙特阿拉伯",
  "塞内加尔",
  "塞尔维亚",
  "塞舌尔",
  "塞拉利昂",
  "新加坡",
  "斯洛伐克",
  "斯洛文尼亚",
  "所罗门群岛",
  "索马里",
  "南非",
  "韩国",
  "南苏丹",
  "西班牙",
  "斯里兰卡",
  "苏丹",
  "苏里南",
  "瑞典",
  "瑞士",
  "叙利亚",
  "塔吉克斯坦",
  "坦桑尼亚",
  "泰国",
  "东帝汶",
  "多哥",
  "汤加",
  "特立尼达和多巴哥",
  "突尼斯",
  "土耳其",
  "土库曼斯坦",
  "图瓦卢",
  "乌干达",
  "乌克兰",
  "阿联酋",
  "英国",
  "美国",
  "乌拉圭",
  "乌兹别克斯坦",
  "瓦努阿图",
  "梵蒂冈",
  "委内瑞拉",
  "越南",
  "也门",
  "赞比亚",
  "津巴布韦",
];

export const ALERT_TYPE_OPTIONS = [
  { value: "upper", label: "Upper" },
  { value: "lower", label: "Lower" },
];

export const CONDITION_OPTIONS = [
  { value: "greater", label: "Greater than (>)" },
  { value: "less", label: "Less than (<)" },
];

// TradingView Charts
export const MARKET_OVERVIEW_WIDGET_CONFIG = {
  colorTheme: "dark", // dark mode
  dateRange: "12M", // last 12 months
  locale: "zh_CN", // language
  largeChartUrl: "", // link to a large chart if needed
  isTransparent: true, // makes background transparent
  showFloatingTooltip: true, // show tooltip on hover
  plotLineColorGrowing: "#0FEDBE", // line color when price goes up
  plotLineColorFalling: "#0FEDBE", // line color when price falls
  gridLineColor: "rgba(240, 243, 250, 0)", // grid line color
  scaleFontColor: "#DBDBDB", // font color for scale
  belowLineFillColorGrowing: "rgba(41, 98, 255, 0.12)", // fill under line when growing
  belowLineFillColorFalling: "rgba(41, 98, 255, 0.12)", // fill under line when falling
  belowLineFillColorGrowingBottom: "rgba(41, 98, 255, 0)",
  belowLineFillColorFallingBottom: "rgba(41, 98, 255, 0)",
  symbolActiveColor: "rgba(15, 237, 190, 0.05)", // highlight color for active symbol
  tabs: [
    {
      title: "Financial",
      symbols: [
        { s: "NYSE:JPM", d: "JPMorgan Chase" },
        { s: "NYSE:WFC", d: "Wells Fargo Co New" },
        { s: "NYSE:BAC", d: "Bank Amer Corp" },
        { s: "NYSE:HSBC", d: "Hsbc Hldgs Plc" },
        { s: "NYSE:C", d: "Citigroup Inc" },
        { s: "NYSE:MA", d: "Mastercard Incorporated" },
      ],
    },
    {
      title: "Technology",
      symbols: [
        { s: "NASDAQ:AAPL", d: "Apple" },
        { s: "NASDAQ:GOOGL", d: "Alphabet" },
        { s: "NASDAQ:MSFT", d: "Microsoft" },
        { s: "NASDAQ:FB", d: "Meta Platforms" },
        { s: "NYSE:ORCL", d: "Oracle Corp" },
        { s: "NASDAQ:INTC", d: "Intel Corp" },
      ],
    },
    {
      title: "Services",
      symbols: [
        { s: "NASDAQ:AMZN", d: "Amazon" },
        { s: "NYSE:BABA", d: "Alibaba Group Hldg Ltd" },
        { s: "NYSE:T", d: "At&t Inc" },
        { s: "NYSE:WMT", d: "Walmart" },
        { s: "NYSE:V", d: "Visa" },
      ],
    },
  ],
  support_host: "https://www.tradingview.com", // TradingView host
  backgroundColor: "#141414", // background color
  width: "100%", // full width
  height: 600, // height in px
  showSymbolLogo: true, // show logo next to symbols
  showChart: true, // display mini chart
};

export const HEATMAP_WIDGET_CONFIG = {
  dataSource: "SPX500",
  blockSize: "market_cap_basic",
  blockColor: "change",
  grouping: "sector",
  isTransparent: true,
  locale: "zh_CN",
  symbolUrl: "",
  colorTheme: "dark",
  exchanges: [],
  hasTopBar: false,
  isDataSetEnabled: false,
  isZoomEnabled: true,
  hasSymbolTooltip: true,
  isMonoSize: false,
  width: "100%",
  height: "600",
};

export const TOP_STORIES_WIDGET_CONFIG = {
  displayMode: "regular",
  feedMode: "market",
  colorTheme: "dark",
  isTransparent: true,
  locale: "zh_CN",
  market: "stock",
  width: "100%",
  height: "600",
};

export const MARKET_DATA_WIDGET_CONFIG = {
  title: "Stocks",
  width: "100%",
  height: 600,
  locale: "zh_CN",
  showSymbolLogo: true,
  colorTheme: "dark",
  isTransparent: false,
  backgroundColor: "#0F0F0F",
  symbolsGroups: [
    {
      name: "Financial",
      symbols: [
        { name: "NYSE:JPM", displayName: "JPMorgan Chase" },
        { name: "NYSE:WFC", displayName: "Wells Fargo Co New" },
        { name: "NYSE:BAC", displayName: "Bank Amer Corp" },
        { name: "NYSE:HSBC", displayName: "Hsbc Hldgs Plc" },
        { name: "NYSE:C", displayName: "Citigroup Inc" },
        { name: "NYSE:MA", displayName: "Mastercard Incorporated" },
      ],
    },
    {
      name: "Technology",
      symbols: [
        { name: "NASDAQ:AAPL", displayName: "Apple" },
        { name: "NASDAQ:GOOGL", displayName: "Alphabet" },
        { name: "NASDAQ:MSFT", displayName: "Microsoft" },
        { name: "NASDAQ:FB", displayName: "Meta Platforms" },
        { name: "NYSE:ORCL", displayName: "Oracle Corp" },
        { name: "NASDAQ:INTC", displayName: "Intel Corp" },
      ],
    },
    {
      name: "Services",
      symbols: [
        { name: "NASDAQ:AMZN", displayName: "Amazon" },
        { name: "NYSE:BABA", displayName: "Alibaba Group Hldg Ltd" },
        { name: "NYSE:T", displayName: "At&t Inc" },
        { name: "NYSE:WMT", displayName: "Walmart" },
        { name: "NYSE:V", displayName: "Visa" },
      ],
    },
  ],
};

export const SYMBOL_INFO_WIDGET_CONFIG = (symbol: string) => ({
  symbol: symbol.toUpperCase(),
  colorTheme: "dark",
  isTransparent: true,
  locale: "zh_CN",
  width: "100%",
  height: 170,
});

export const CANDLE_CHART_WIDGET_CONFIG = (symbol: string) => ({
  allow_symbol_change: false,
  calendar: false,
  details: true,
  hide_side_toolbar: true,
  hide_top_toolbar: false,
  hide_legend: false,
  hide_volume: false,
  hotlist: false,
  interval: "D",
  locale: "zh_CN",
  save_image: false,
  style: 1,
  symbol: symbol.toUpperCase(),
  theme: "dark",
  timezone: "Etc/UTC",
  backgroundColor: "#141414",
  gridColor: "#141414",
  watchlist: [],
  withdateranges: false,
  compareSymbols: [],
  studies: [],
  width: "100%",
  height: 600,
});

export const BASELINE_WIDGET_CONFIG = (symbol: string) => ({
  allow_symbol_change: false,
  calendar: false,
  details: false,
  hide_side_toolbar: true,
  hide_top_toolbar: false,
  hide_legend: false,
  hide_volume: false,
  hotlist: false,
  interval: "D",
  locale: "zh_CN",
  save_image: false,
  style: 10,
  symbol: symbol.toUpperCase(),
  theme: "dark",
  timezone: "Etc/UTC",
  backgroundColor: "#141414",
  gridColor: "#141414",
  watchlist: [],
  withdateranges: false,
  compareSymbols: [],
  studies: [],
  width: "100%",
  height: 600,
});

export const TECHNICAL_ANALYSIS_WIDGET_CONFIG = (symbol: string) => ({
  symbol: symbol.toUpperCase(),
  colorTheme: "dark",
  isTransparent: "true",
  locale: "zh_CN",
  width: "100%",
  height: 400,
  interval: "1h",
  largeChartUrl: "",
});

export const COMPANY_PROFILE_WIDGET_CONFIG = (symbol: string) => ({
  symbol: symbol.toUpperCase(),
  colorTheme: "dark",
  isTransparent: "true",
  locale: "zh_CN",
  width: "100%",
  height: 440,
});

export const COMPANY_FINANCIALS_WIDGET_CONFIG = (symbol: string) => ({
  symbol: symbol.toUpperCase(),
  colorTheme: "dark",
  isTransparent: "true",
  locale: "zh_CN",
  width: "100%",
  height: 464,
  displayMode: "regular",
  largeChartUrl: "",
});

export const POPULAR_STOCK_SYMBOLS = [
  // Tech Giants (the big technology companies)
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "TSLA",
  "META",
  "NVDA",
  "NFLX",
  "ORCL",
  "CRM",

  // Growing Tech Companies
  "ADBE",
  "INTC",
  "AMD",
  "PYPL",
  "UBER",
  "ZOOM",
  "SPOT",
  "SQ",
  "SHOP",
  "ROKU",

  // Newer Tech Companies
  "SNOW",
  "PLTR",
  "COIN",
  "RBLX",
  "DDOG",
  "CRWD",
  "NET",
  "OKTA",
  "TWLO",
  "ZM",

  // Consumer & Delivery Apps
  "DOCU",
  "PTON",
  "PINS",
  "SNAP",
  "LYFT",
  "DASH",
  "ABNB",
  "RIVN",
  "LCID",
  "NIO",

  // International Companies
  "XPEV",
  "LI",
  "BABA",
  "JD",
  "PDD",
  "TME",
  "BILI",
  "DIDI",
  "GRAB",
  "SE",
];

export const NO_MARKET_NEWS =
  '<p class="mobile-text" style="margin:0 0 20px 0;font-size:16px;line-height:1.6;color:#4b5563;">No market news available today. Please check back tomorrow.</p>';

export const WATCHLIST_TABLE_HEADER = [
  "Company",
  "Symbol",
  "Price",
  "Change",
  "Market Cap",
  "P/E Ratio",
  "Alert",
  "Action",
];
